### ISSUE TITLE
Integrate devicetree overlay into image

### ISSUE THREAD

**Issue by linuxianer99** [Openvario/ovbuild-container#11]
Integrate DT overlay into to image for raspberry pi

**Comment by linuxianer99** [comment]
@lordfolken : Currently i make no good progress as i don't find the clue where to add the DTBO.
I have a recipe to compile to DTS to DTBO but it will not be installed into /boot/overlays ...

Do you have an idea ?

**Comment by lordfolken** [comment]
Ill built it tonight and will have a look .

**Comment by linuxianer99** [comment]
Managed it yesterday evening :-)
