### ISSUE TITLE
The automatic building of the docker image and container not functional

### ISSUE THREAD

**Issue by August2111** [Openvario/ovbuild-container#4]
Unfortunately the automatic building of the docker image/container with command
```sudo docker run -it --rm -v $(pwd):/workdir openvario/ovbuild --workdir=/workdir```
isn't functional...
With linuxianer99/ovbuild I get only the ubuntu-18.04 dockerfile, no debian-11.

**Comment by linuxianer99** [comment]
That is correct behaviour ;-)

can you please try 

`docker run -it --rm -v $(pwd):/workdir ghcr.io/openvario/ovbuild-container:main --workdir=/workdir`

??

**Comment by August2111** [comment]
Now it looks fine :)
With this this and a small change in the manifest/default.xml file the OpenVario is buildable!
Because the hardknott branch of the meta-openvario layer is real a copy of the warrior branch, you has either to change one line in the local default.xml file   
```  <remote name="ov" fetch="git://github.com/August2111" />```  (line 10)
from Openvario to August2111 or - the better solution - the PR is merged to Openvario

**Comment by August2111** [comment]
Solved :)
